name: CI

on:
  pull_request:
    branches: [ master, release ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 10.16
    - name: Install dependencies
      uses: CultureHQ/actions-yarn@master
      with:
        args: install
    - name: Test
      uses: CultureHQ/actions-yarn@master
      with:
        args: test
