name: Publish

on:
  push:
    branches: [ release ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 10.16
    - name: Install dependencies
      uses: CultureHQ/actions-yarn@master
      with:
        args: install
    - name: Build
      uses: CultureHQ/actions-yarn@master
      with:
        args: build

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 10.16
        registry-url: https://registry.npmjs.org/
    - run: cd lib
    - run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

